# Generated by Django 4.0.1 on 2022-02-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_subject_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
